-- INSERT INTO tienda.categories(name) VALUES ('Books');
-- INSERT INTO tienda.categories(name) VALUES ('Costumers');
-- INSERT INTO tienda.categories(name) VALUES ('Fitness');
-- INSERT INTO tienda.categories(name) VALUES ('Movies');
-- INSERT INTO tienda.categories(name) VALUES ('Music');
-- INSERT INTO tienda.categories(name) VALUES ('Sports');
-- INSERT INTO tienda.categories(name) VALUES ('Toys');
-- INSERT INTO tienda.categories(name) VALUES ('Video Games');